/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVAULT,
  IVAULTInterface,
} from "../../../interfaces/VaultInterface.sol/IVAULT";

const _abi = [
  {
    inputs: [],
    name: "donate",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVAULT__factory {
  static readonly abi = _abi;
  static createInterface(): IVAULTInterface {
    return new Interface(_abi) as IVAULTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVAULT {
    return new Contract(address, _abi, runner) as unknown as IVAULT;
  }
}
